# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='images/article_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='images/article_thumbnails/default.png', upload_to='images/article_thumbnails'),
        ),
    ]
