# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 23:21
from __future__ import unicode_literals

import blog.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171003_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=blog.services.get_random_thumbnail, upload_to='images/article_thubnails'),
        ),
    ]
